/*
*  Include files
*/
#include "../pblas.h"
#include "../PBpblas.h"
#include "../PBtools.h"
#include "../PBblacs.h"
#include "../PBblas.h"

//WCC:add
// To disable warnings generated by gcc-9.
void wcc_Cigebs2d(int ConTxt, char *scope, char *top, int m, int n, char *A,
                  int lda)
{
   Cigebs2d(ConTxt, scope, top, m, n, (int*) A, lda);
}
void wcc_Cigebr2d(int ConTxt, char *scope, char *top, int m, int n, char *A,
                  int lda, int rsrc, int csrc)
{
   Cigebr2d(ConTxt, scope, top, m, n, (int*) A, lda, rsrc, csrc);
}
